import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import AdminSidebar from "@/componenets/admin/AdminSidebar";
import AdminHeader from "@/componenets/admin/AdminHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminSidebar />
        <AdminHeader />
        <div className="ml-0 md:ml-[245px]"
          style={{ backgroundColor: "var(--color-gray)" }}
        >

          {children}
        </div>

      </body>
    </html>
  );
}
